- name: Install fedora 24 and it's configurations
  hosts: fedora
  gather_facts: false
  become: true
  roles:
    - repos
    - common
    - rails
    - java
    - docker
    - golang
      #- ruby
      #- nodejs



