- name: Install fedora 24 and it's configurations
  hosts: fedora
  gather_facts: false
  become: true
  roles:
    - repos
    - common
    - rails
    - java
    - docker
    - golang

- name: golang
  hosts: all
  gather_facts: true
  become: true
  roles:
    - golang
  tags:
    - golang
