- name: Install fedora 28 and it's configurations
  hosts: fedora
  gather_facts: false
  become: true
  roles:
    - repos
    - common
    - rails
    - java
    - docker

- name: tools
  hosts: all
  gather_facts: true
  become: true
  roles:
    - tools
  tags:
    - tools

- name: tmux
  hosts: all
  gather_facts: true
  become: true
  roles:
    - tmux
  tags:
    - tmux

- name: golang
  hosts: all
  gather_facts: true
  become: true
  roles:
    - golang
  tags:
    - golang

- name: common
  hosts: all
  gather_facts: true
  become: true
  roles:
    - common
  tags:
    - common

- name:  magxitrackpad2
  hosts: all
  gather_facts: true
  become: true
  roles:
    - magictrackpad2
  tags:
    - magictrackpad2

- name: powerline-shell
  hosts: all
  gather_facts: true
  become: true
  roles:
    - powerline-shell
  tags:
    - powerline-shell

