- name: download pet cli snippet manager
  become: true
  become_user: root
  yum:
    name: https://github.com/knqyf263/pet/releases/download/v0.3.0/pet_0.3.0_linux_amd64.rpm
    state: present
  when: OS == "Linux"

- name: download pet
  homebrew:
    name: knqyf263/pet/pet
    state: present
  when: OS == "MacOS"

- name: install custom system admin tools -- Linux
  become: true
  become_user: root
  dnf:
    name: ['fd-find', 'bat', 'exa', 'fzf']
    state: present
  when: OS == "Linux"

- name: install custom system admin tools -- MacOS
  homebrew:
    name: ['bat', 'exa', 'fzf', 'jid', 'httpie', 'docker', 'tree', 'reattach-to-user-namespace']
    state: present
  when: OS == "MacOS"

- name: download and untar fasd
  unarchive:
    src: https://github.com/clvv/fasd/tarball/1.0.1
    dest: ~/Downloads/
    remote_src: yes
  when: OS == "Linux"

- name: install fasd
  shell: cd ~/Downloads/clvv-fasd-4822024 && sudo make install
  when: OS == "Linux"

- name: install fasd on macos
  homebrew:
    name: fasd
    state: present
  when: OS == "MacOS"

- name: create symbolic link for vim
  file:
    src: ~/personal/system/vimrc
    dest: ~/.vimrc
    state: link

- name: create bundle drectory
  file:
    dest: ~/.vim/bundle
    state: directory

- name: clone vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim

- name: install minikube
  shell: brew cask install minikube
  when: OS == "MacOS"

- name: install glances
  pip:
    name:
      - glances
    extra_args: --user
