- name: get checkout smetroid repo
  git:
    repo: https://github.com/smetroid/system.git
    dest: ~/personal/system

- name: install powerline
  pip:
    name:
      - powerline-shell
    extra_args: --user

- name: add powerline-shell lines to .bashrc
  blockinfile:
    path: ~/.bashrc
    block: |
      function _update_ps1() {
        PS1=$(powerline-shell $?)
      }

      if [[ $TERM != linux && ! $PROMPT_COMMAND =~ _update_ps1 ]]; then
        PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
      fi

- name: create .config directory
  file:
    path: ~/.config
    state: directory

- name: create symbolic link smetroid powerline-shell config directory
  file:
    src: ~/personal/system/config/powerline-shell
    dest: ~/.config/powerline-shell
    state: link

