- name: check if my personal system repo exists
  stat:
    path: ~/personal/system
  register: metroid

- name: get checkout smetroid repo
  git:
    repo: https://github.com/smetroid/system.git
    dest: ~/personal/system
  when: metroid.stat.exists == false

- name: install powerline
  pip:
    name:
      - powerline-shell
    extra_args: --user

- name: add powerline-shell lines to .bashrc
  blockinfile:
    path: ~/.bashrc
    block: |
      function _update_ps1() {
        PS1=$(powerline-shell $?)
      }

      if [[ $TERM != linux && ! $PROMPT_COMMAND =~ _update_ps1 ]]; then
        PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
      fi

- name: create .config directory
  file:
    path: ~/.config
    state: directory

- name: create symbolic link smetroid powerline-shell config directory
  file:
    src: ~/personal/system/config/powerline-shell
    dest: ~/.config/powerline-shell
    state: link

- name:  make local share fonts directory
  file:
    path: ~/.local/share/fonts
    state: directory
    #command: mkdir -p ~/.local/share/fonts
  when: OS == "Linux"

- name: download fonts for linux
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20Nerd%20Font%20Complete.otf
    dest: ~/.local/share/fonts/Droid Sans Mono for Powerline Nerd Font Complete.otf
  when: OS == "Linux"

- name: download fonts for macos
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20Nerd%20Font%20Complete.otf
    dest: ~/Library/Fonts/Droid Sans Mono for Powerline Nerd Font Complete.otf
  when: OS == "MacOS"



