- name: install development tools
  dnf: name="@development tools" state=present
  tags: development

- name: lxde desktop
  dnf: name="@LXDE" state=present

- name: install vim-minimal
  dnf: name=vim-minimal state=present

- name: update vim-minimal to match the version of vim-common
  dnf: name=vim-minimal state=latest

- name: common package items
  dnf: name={{ item }} state=present
  with_items:
    - copyq
      #    - teamviewer
    - chromium
      #    - vivaldi
    - git
    - ruby
    - gvim
    - vim-enhanced
    - vim-X11
    - kdiff3
    - keepassx
    - sqlite
    - sqlitebrowser
    - geary
    - remmina
      #- synchthing
    - golang
    - vagrant
    - virt-manager
    - virt-viewer
    - inkscape
    - blender
    - x2goagent
    - x2goserver
    - x2goclient
    - cups-x2go
    - x2goplugin
    - x2goserver-xsession
    - x2goserver-printing
    - x2goserver-fmbindings
    - x2godesktopsharing
    - xpra
    - xpra-html5
    - nmap
    - xorg-x11-* #without this lxde won't work
    - autokey-qt
    - xdotool
    - qemu
    - libvirt
    - libxml2-devel
    - libxslt-devel

- name: create /opt/idea directory to install intellij
  file:
    path: /opt/idea
    state: directory
    mode: 0755

    #- name: check to see if {{ idea_tar_file }} is already downloaded
    #  stat:
    #    path: /opt/idea/{{ idea_tar_file }}
    #  register: intellij_downloaded
    #
    #  #- debug: var=intellij_downloaded
    #
    #- name: download IntelliJ
    #  get_url:
    #    url: https://download.jetbrains.com/idea/{{ idea_tar_file }}
    #    dest: /opt/idea/
    #  when: intellij_downloaded.stat.exists == False
    #
    #- name: untar intelliJ to /opt/idea/
    #  shell: tar -xvzf /opt/idea/{{ idea_tar_file }}
    #  when: intellij_downloaded.stat.exists == False

    #- name: install kdeenlive for video editing
    #dnf: name=kdenlive state=present

  #- name: install virtualbox
  #dnf: name={{item}} state=present
  #with_items:
  #  - VirtualBox
  #  - akmod-VirtualBox
  #- kernel-devel
  #- name: install tmux version {{ tmux_version }}
  #dnf: name=tmux-{{ tmux_version }} state=present

- name: set the graphical.target as default
  shell: systemctl set-default graphical.target


